### ISSUE TITLE
Distribution doesn't include py.typed files.

### ISSUE THREAD

**Issue by asford** [shabbyrobe/grpc-stubs#18]
The current distribution package doesn't include the `py.typed` files in this repo.
This isn't a blocker, as they aren't [strictly required](https://www.python.org/dev/peps/pep-0561/#stub-only-packages) in a stub-only package.
However this may be unexpected?

**Comment by shabbyrobe** [comment]
Ah thank you, it was indeed unexpected. I've pushed a fix, but I'll hold fire on releasing until the next time I need to push to PyPi. If this is disrupting you though, please let me know and I'll push it out right away.

**Comment by asford** [comment]
Thanks for the quick response and work on these stubs. This isn't blocking
so the "on next pypi release" would be fine
