### ISSUE TITLE
can mypy be optional dependency?

### ISSUE THREAD

**Issue by jizhilong** [shabbyrobe/grpc-stubs#27]
Hi,
   thanks for this awesome project, it really helps a lot. As the title say, can mypy be an install dependency? In many scenarios, pyi stubs are used for augmenting Pycharm auto-completement instead of type-check jobs, without installing mypy, tens of megabytes of packages will be reduced from the virtual env.

**Comment by shabbyrobe** [comment]
Yep I think it's probably not necessary as a direct dependency at all. Just pushed 1.24.8 with mypy moved into requirements-dev.txt via 6c5966073b10da50d1f4096eee1fb7d494649708. Please let me know if it does the trick for you.

**Comment by jizhilong** [comment]
> Just pushed 1.24.8 with mypy moved into requirements-dev.txt via https://github.com/shabbyrobe/grpc-stubs/commit/6c5966073b10da50d1f4096eee1fb7d494649708.

It works well for me, Thanks a lot.
