### ISSUE TITLE
Argument `grace` of Server.stop() should be Optional[float]

### ISSUE THREAD

**Issue by adriansahlman** [shabbyrobe/grpc-stubs#6]
Hey, thanks for making this stub. Has been super useful for me!

I was looking into what type to use for the argument `grace` of `Server.stop()` when creating a delegate and to figure it out I took a peek at the gRPC source code for python. The only place that this argument is used seems to be [here](https://github.com/grpc/grpc/blob/80bdca9b68aab75950f2712585d43e544e9bf186/src/python/grpcio/grpc/_server.py#L906). It is passed to `threading.Event.wait()` which according to the [docs](https://docs.python.org/3/library/threading.html#threading.Event.wait) takes an optional floating point number.

So I believe the correct type for the argument should be `typing.Optional[float]`.

Cheers!

**Comment by shabbyrobe** [comment]
That looks right, yep! Thanks for the report, v1.24.2 has been uploaded to pypi with the fix. Much appreciated!
